CREATE TABLE BOOKS(
BookId INT IDENTITY(1,1) PRIMARY KEY,
BookName VARCHAR (500),
AuthorName VARCHAR(20),
Rating VARCHAR(300),
TotalCountRating INT,
DiscountPrice INT,
OriginalPrice INT,
Description VARCHAR (500),
BookImage VARCHAR (200),
BookCount INT NOT NULL
);

SELECT * FROM BOOKS



CREATE TABLE CART(
CartId INT  IDENTITY(1,1) PRIMARY KEY,
UserId  INT NOT NULL FOREIGN KEY (UserId) REFERENCES UserDetails(UserId),
BookId INT NOT NULL FOREIGN KEY (BookId) REFERENCES Books(BookId),
Quantity INT DEFAULT 1
);


CREATE TABLE ADDRESS(
	
	AddressId INT  IDENTITY(1,1) PRIMARY KEY,
	Address VARCHAR (500),
	City VARCHAR (30),
	State VARCHAR (40),
	UserId  INT NOT NULL FOREIGN KEY (UserId) REFERENCES UserDetails(UserId)
);

DROP TABLE ADDRESS

SELECT * FROM ADDRESS

CREATE TABLE ORDERTABLE(
OrderId INT  IDENTITY(1,1) PRIMARY KEY,
UserId  INT NOT NULL FOREIGN KEY (UserId) REFERENCES UserDetails(UserId),
BookId INT NOT NULL FOREIGN KEY (BookId) REFERENCES Books(BookId),
AddressId INT NOT NULL FOREIGN KEY (AddressId) REFERENCES ADDRESS(AddressId)
);


CREATE TABLE FEEDBACK(
FeedBackId INT  IDENTITY(1,1) PRIMARY KEY,
UserId  INT NOT NULL FOREIGN KEY (UserId) REFERENCES UserDetails(UserId),
BookId INT NOT NULL FOREIGN KEY (BookId) REFERENCES Books(BookId)
);

CREATE TABLE ADMIN(
	OrderId INT NOT NULL FOREIGN KEY (OrderId) REFERENCES ORDERTABLE(OrderId),
	EmailUs varchar(5000) NOT NULL,
	ContactUs varchar(5000) NOT NULL,
	Address varchar(5000)NOT NULL
);